
export const AUTH_REQ="AUTH_REQUEST";
export const AUTH_SUCCESS="AUTH_SUCCESS";
export const AUTH_FAILURE="AUTH_FAILUE";
export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGOUT_REQUEST="LOGOUT_RESQUEST"