@startuml
'https://plantuml.com/class-diagram

Cliente -- ContaCliente
ContaCliente -- Produto
ContaCliente -- Pago
ContaCliente -- Divida
Divida -- Pago

class Cliente {
-nome: String
-conta: ContaCliente

}

class ContaCliente {
-data: LocalDate
-cliente: Cliente
-valor: Double
-quantidade: Integer
-dividas: List<Divida>

}

class Pago {
-data: LocalDate
-divida: List<Divida>
-conta: contaCliente
}

class Divida {
-data: LocalDate
-quantidade
-produto: Produto
}

class Produto {
-descrição: String
-preço: Double
}

@enduml